name: build_docs
on:
  push:
    branches:
      - main 

  pull_request:

  schedule:
      - cron: "0 5 * * 1"  # runs at 05:00 UTC on Mondays

jobs:
  build:
    runs-on: macos-11
    env:
      configuration: Release
    strategy:
      fail-fast: true
      max-parallel: 4
    steps:
      - name: Install
        run: |
          brew install doxygen -y
          brew install graphviz -y
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build
        run: |
          cd ./build/
          doxygen
          cd ../
      - name: Copy files to docs
        run: |
          rm -rf ./docs
          mkdir -p ./docs
          cp -r ./build/doxygen_output/html/* ./docs
          cp -r ./build/yapre/docs ./docs/docs
          mkdir -p ./docs/vis
          cp -r ./build/yapre/vis/png ./docs/vis/png
          touch ./docs/.nojekyll 
      - name: Commit and push
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Github Action Auto Build'
          add: '*.* --force'
          cwd: './docs/'
